name: Extract, Load, Transform, and Analytics (Dev)

on:
  pull_request:
    branches:
      - main
    paths:
      # TODO - some jobs can be triggered even if no related paths were changed
      # There is a workaround solution applied in:
      #   https://github.com/gooddata/gdc-nas/blob/master/.github/workflows/pre-merge-pipeline.yml
      # Shared
      - .github/workflows/elta_dev.yml
      - .github/workflows/reusable_elta.yml
      # Build custom Meltano image
      - data_pipeline/requirements-meltano.txt
      - data_pipeline/meltano-plugins.yml
      - data_pipeline/plugins/**/*.lock
      - Dockerfile_meltano
      - Dockerfile_dbt
      - Dockerfile_gooddata
      # Extract load
      - data_pipeline/meltano.yml
      - data_pipeline/meltano_conf/**/*
      - data_pipeline/requirements-meltano.txt
      - .github/workflows/reusable_extract_load.yml
      # Transform
      - data_pipeline/macros/**/*
      - data_pipeline/models/**/*
      - data_pipeline/profile/**/*
      - data_pipeline/dbt_project.yml
      - data_pipeline/packages.yml
      - data_pipeline/requirements-dbt.txt
      - data_pipeline/requirements-gooddata.txt
      - .github/workflows/reusable_transform.yml
      # Analytics
      - data_pipeline/gooddata_layouts/**/*
      - data_pipeline/requirements-gooddata.txt
      - .github/workflows/reusable_analytics.yml

jobs:
  build-images:
    uses: ./.github/workflows/reusable_builds.yml
    secrets: inherit

  elta:
    needs:
      - build-images
    uses: ./.github/workflows/reusable_elta.yml
    with:
      ENVIRONMENT: "dev"
    secrets: inherit

  elta-cloud:
    needs:
      - build-images
    uses: ./.github/workflows/reusable_elta.yml
    with:
      ENVIRONMENT: "dev_cloud"
      DBT_CLOUD: "true"
    secrets: inherit
