name: Extract, Load, Transform, and Analytics (Staging/Production)

on:
  push:
    branches:
      - main
      - prod
    paths:
      # TODO - some jobs can be triggered even if no related paths were changed
      # There is a workaround solution applied in:
      #   https://github.com/gooddata/gdc-nas/blob/master/.github/workflows/pre-merge-pipeline.yml
      # Shared
      - .github/workflows/elta_staging_prod.yml
      - .github/workflows/reusable_elta.yml
      # Extract load
      - data_pipeline/meltano.yml
      - data_pipeline/meltano_conf/**/*
      - data_pipeline/requirements-meltano.txt
      - .github/workflows/reusable_extract_load.yml
      # Transform
      - data_pipeline/macros/**/*
      - data_pipeline/models/**/*
      - data_pipeline/profile/**/*
      - data_pipeline/dbt_project.yml
      - data_pipeline/packages.yml
      - data_pipeline/requirements-dbt.txt
      - data_pipeline/requirements-gooddata.txt
      - .github/workflows/reusable_transform.yml
      # Analytics
      - data_pipeline/gooddata_layouts/**/*
      - data_pipeline/requirements-gooddata.txt
      - .github/workflows/reusable_analytics.yml

jobs:
  elta:
    name: ELTA (${{ github.ref == 'refs/heads/main' && 'staging' || 'prod' }})
    uses: ./.github/workflows/reusable_elta.yml
    with:
      ENVIRONMENT: "${{ github.ref == 'refs/heads/main' && 'staging' || 'prod' }}"
    secrets: inherit

  elta-cloud:
    name: ELTA cloud (${{ github.ref == 'refs/heads/main' && 'staging' || 'prod' }})
    uses: ./.github/workflows/reusable_elta.yml
    with:
      ENVIRONMENT: "${{ github.ref == 'refs/heads/main' && 'staging' || 'prod' }}_cloud"
      DBT_CLOUD: "true"
    secrets: inherit
