name: Extract, Load, Transform, and Analytics (Staging)

on:
  push:
    branches:
      - main
      - prod
    paths:
      # TODO - some jobs can be triggered even if no related paths were changed
      # There is a workaround solution applied in:
      #   https://github.com/gooddata/gdc-nas/blob/master/.github/workflows/pre-merge-pipeline.yml
      # Shared
      - .github/workflows/elta_staging_prod.yml
      # Extract load
      - data_pipeline/meltano.yml
      - data_pipeline/meltano_conf/**/*
      - data_pipeline/requirements-meltano.txt
      - .github/workflows/reusable_extract_load.yml
      # Transform
      - data_pipeline/macros/**/*
      - data_pipeline/models/**/*
      - data_pipeline/profile/**/*
      - data_pipeline/dbt_project.yml
      - data_pipeline/packages.yml
      - data_pipeline/requirements-dbt.txt
      - data_pipeline/requirements-gooddata.txt
      - .github/workflows/reusable_transform.yml
      # Analytics
      - data_pipeline/gooddata_layouts/**/*
      - data_pipeline/requirements-gooddata.txt
      - .github/workflows/reusable_analytics.yml

jobs:
  ####################################
  # Extract load
  extract-load-staging:
    uses: ./.github/workflows/reusable_extract_load.yml
    with:
      ENVIRONMENT: "staging"
      FULL_REFRESH: "false" # TODO: define workflow_dispatch with this parameter and set it here
      MELTANO_CUSTOM_IMAGE: "ghcr.io/${{ github.repository }}/${{ vars.MELTANO_CUSTOM_IMAGE_BASE }}:${{ vars.MELTANO_VERSION }}"
    secrets: inherit
  ####################################
  # Transform
  transform-staging:
    needs:
      - extract-load-staging
    uses: ./.github/workflows/reusable_transform.yml
    with:
      ENVIRONMENT: "staging"
      FULL_REFRESH: "false" # TODO: define workflow_dispatch with this parameter and set it here
      DBT_CUSTOM_IMAGE: "ghcr.io/${{ github.repository }}/${{ vars.DBT_CUSTOM_IMAGE_BASE }}:${{ vars.DBT_VERSION }}"
    secrets: inherit
  ####################################
  # Transform
  analytics-staging:
    needs:
      - transform-staging
    uses: ./.github/workflows/reusable_analytics.yml
    with:
      ENVIRONMENT: "staging"
      GOODDATA_CUSTOM_IMAGE: "ghcr.io/${{ github.repository }}/${{ vars.GOODDATA_IMAGE_BASE }}:${{ vars.GOODDATA_VERSION }}"
    secrets: inherit
