name: Reusable Builds

on:
  workflow_call:
    inputs:
      MELTANO_CUSTOM_IMAGE:
        required: true
        type: string
      DBT_CUSTOM_IMAGE:
        required: true
        type: string
      GOODDATA_SDK_CUSTOM_IMAGE:
        required: true
        type: string
      MELTANO_VERSION:
        required: true
        type: string
      DBT_VERSION:
        required: true
        type: string
      GOODDATA_SDK_VERSION:
        required: true
        type: string
      PYTHON_IMAGE:
        required: true
        type: string
      IMAGES_WORKDIR:
        required: true
        type: string

jobs:
  build-and-push-custom-meltano-image:
    uses: ./.github/workflows/reusable_build.yml
    with:
      NAME: build-meltano
      TAGS: |
        ${{ inputs.MELTANO_CUSTOM_IMAGE }}
      DOCKER_FILE: Dockerfile_meltano
      BUILD_ARGS: |
        MELTANO_VERSION=${{ inputs.MELTANO_VERSION }}
        IMAGES_WORKDIR=${{ inputs.IMAGES_WORKDIR }}
    secrets: inherit
  build-and-push-custom-dbt-image:
    uses: ./.github/workflows/reusable_build.yml
    with:
      NAME: build-dbt
      TAGS: |
        ${{ inputs.DBT_CUSTOM_IMAGE }}
      DOCKER_FILE: Dockerfile_dbt
      BUILD_ARGS: |
        DBT_VERSION=${{ inputs.DBT_VERSION }}
        IMAGES_WORKDIR=${{ inputs.IMAGES_WORKDIR }}
    secrets: inherit
  build-and-push-custom-gooddata-image:
    uses: ./.github/workflows/reusable_build.yml
    with:
      NAME: build-gooddata
      TAGS: |
        ${{ inputs.GOODDATA_SDK_CUSTOM_IMAGE }}
      DOCKER_FILE: Dockerfile_gooddata
      BUILD_ARGS: |
        PYTHON_IMAGE=${{ inputs.PYTHON_IMAGE }}
        IMAGES_WORKDIR=${{ inputs.IMAGES_WORKDIR }}
    secrets: inherit
