name: Reusable ELTA

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      BRANCH_NAME:
        type: string
      DEPLOY_GD_MODELS:
        required: false
        type: string
        default: "true"
      DBT_CLOUD:
        required: false
        type: string
        default: "false"
      DB_OVERRIDE:
        required: false
        type: string
        default: ""
      FULL_REFRESH:
        required: false
        type: string
        default: "false"
      MELTANO_CUSTOM_IMAGE:
        required: true
        type: string
      DBT_CUSTOM_IMAGE:
        required: true
        type: string
      GOODDATA_SDK_CUSTOM_IMAGE:
        required: true
        type: string

jobs:
  ####################################
  # Extract load
  extract-load:
    uses: ./.github/workflows/reusable_extract_load.yml
    with:
      ENVIRONMENT: "${{ inputs.ENVIRONMENT }}"
      DB_OVERRIDE: "${{ inputs.DB_OVERRIDE }}"
      FULL_REFRESH: "${{ inputs.FULL_REFRESH }}"
      MELTANO_CUSTOM_IMAGE: "${{ inputs.MELTANO_CUSTOM_IMAGE }}"
      BRANCH_NAME: "${{ inputs.BRANCH_NAME }}"
    secrets: inherit
  ####################################
  # Transform
  transform:
    needs:
      - extract-load
    uses: ./.github/workflows/reusable_transform.yml
    with:
      ENVIRONMENT: "${{ inputs.ENVIRONMENT }}"
      DB_OVERRIDE: "${{ inputs.DB_OVERRIDE }}"
      FULL_REFRESH: "${{ inputs.FULL_REFRESH }}"
      DBT_CUSTOM_IMAGE: "${{ inputs.DBT_CUSTOM_IMAGE }}"
      BRANCH_NAME: "${{ inputs.BRANCH_NAME }}"
      DBT_CLOUD: "${{ inputs.DBT_CLOUD }}"
      DEPLOY_GD_MODELS: "${{ inputs.DEPLOY_GD_MODELS }}"
    secrets: inherit
  ####################################
  # Analytics
  analytics:
    needs:
      - transform
    uses: ./.github/workflows/reusable_analytics.yml
    with:
      ENVIRONMENT: "${{ inputs.ENVIRONMENT }}"
      DB_OVERRIDE: "${{ inputs.DB_OVERRIDE }}"
      GOODDATA_SDK_CUSTOM_IMAGE: "${{ inputs.GOODDATA_SDK_CUSTOM_IMAGE }}"
      BRANCH_NAME: "${{ inputs.BRANCH_NAME }}"
      DEPLOY_GD_MODELS: "${{ inputs.DEPLOY_GD_MODELS }}"
    secrets: inherit
