on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      DB_OVERRIDE:
        required: false
        type: string
        default: ""
      GOODDATA_SDK_CUSTOM_IMAGE:
        required: true
        type: string
      BRANCH_NAME:
        type: string
      DEPLOY_GD_MODELS:
        required: false
        type: string
        default: "true"

jobs:
  reusable_analytics:
    name: analytics
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    container: ${{ inputs.GOODDATA_SDK_CUSTOM_IMAGE }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.BRANCH_NAME }}

      - name: Setup Environment
        run: |
          mkdir -p ~/.gooddata
          echo ${{ secrets.GOODDATA_PROFILES_FILE }} | base64 --decode > ~/.gooddata/profiles.yaml

      - name: Deploy Analytics
        shell: bash
        if: ${{ inputs.DEPLOY_GD_MODELS == 'true' }}
        run: |
          source .env.${{ inputs.ENVIRONMENT }} ${{ inputs.DB_OVERRIDE }}
          make deploy_analytics

      # Test analytics even when deploy is skipped (DEPLOY_ANALYTICS=false)
      # It is skipped in scheduled runs
      - name: Test Analytics
        shell: bash
        timeout-minutes: 10
        run: |
          source .env.${{ inputs.ENVIRONMENT }} ${{ inputs.DB_OVERRIDE }}
          make test_insights
